export const FETCH_LEADER_BATTLES = 'FETCH_LEADER_BATTLES_v6';
export const FETCH_IGN_BATTLES = 'FETCH_IGN_BATTLES_v6';
export const FETCH_BATTLE_TRANSACTIONS = 'FETCH_BATTLE_TRANSACTIONS_v6';
export const GROUP_CARDS = 'GROUP_CARDS_v6';
export const MIGRATE_BATTLES = 'MIGRATE_BATTLES_v6';
