export const FETCH_LEADER_BATTLES = 'FETCH_LEADER_BATTLES';
export const FETCH_IGN_BATTLES = 'FETCH_IGN_BATTLES';
export const FETCH_BATTLE_TRANSACTIONS = 'FETCH_BATTLE_TRANSACTIONS';
export const GROUP_CARDS = 'GROUP_CARDS';
export const MIGRATE_BATTLES = 'MIGRATE_BATTLES';
